Added Geo/CellCompelex.cpp and Geo/CellComplex.h They construct a cell complex of a finite elemement mesh of a model, and are able to reduce and coreduce it in order to compute model's homology groups.
Also added contrib/kbipack to by Saku Suuriniemi for future use to
compute Smith normal forms of the boundary operator matrices of the
reduced cell complex.

Modified Makefiles and configure.in accordingly.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1277,6 +1277,7 @@ Optional Features:
   --enable-chaco          compile Chaco partitioner (default=yes)
   --enable-tetgen         compile Tetgen if available (default=yes)
   --enable-matheval       compile MathEval if available (default=yes)
+  --enable-kbipack        compile kbipack if available (default=yes)
   --enable-gmm            use gmm++ if available (default=yes)
   --enable-osmesa         use OSMesa for offscreen rendering (default=no)
   --enable-cgns           enable CGNS output (default=no)
@@ -1911,6 +1912,11 @@ if test "${enable_matheval+set}" = set; then
   enableval=$enable_matheval;
 fi
 
+# Check whether --enable-kbipack was given.
+if test "${enable_kbipack+set}" = set; then
+  enableval=$enable_kbipack;
+fi
+
 # Check whether --enable-gmm was given.
 if test "${enable_gmm+set}" = set; then
   enableval=$enable_gmm;
@@ -1978,6 +1984,7 @@ if test "x$enable_minimal" = "xyes"; then
   enable_netgen=no;
   enable_tetgen=no;
   enable_matheval=no;
+  enable_kbipack=no;
   enable_gmm=no;
   enable_ann=no;
   enable_metis=no;
@@ -4743,6 +4750,39 @@ fi
 _ACEOF
 
       BO="${BO} MathEval"
+    fi
+  fi
+
+    if test "x$enable_kbipack" != "xno"; then
+    { echo "$as_me:$LINENO: checking for ./contrib/kbipack/gmp_normal_form.h" >&5
+echo $ECHO_N "checking for ./contrib/kbipack/gmp_normal_form.h... $ECHO_C" >&6; }
+if test "${ac_cv_file___contrib_kbipack_gmp_normal_form_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  test "$cross_compiling" = yes &&
+  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
+echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+if test -r "./contrib/kbipack/gmp_normal_form.h"; then
+  ac_cv_file___contrib_kbipack_gmp_normal_form_h=yes
+else
+  ac_cv_file___contrib_kbipack_gmp_normal_form_h=no
+fi
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_file___contrib_kbipack_gmp_normal_form_h" >&5
+echo "${ECHO_T}$ac_cv_file___contrib_kbipack_gmp_normal_form_h" >&6; }
+if test $ac_cv_file___contrib_kbipack_gmp_normal_form_h = yes; then
+  KBIPACK="yes"
+fi
+
+    if test "x${KBIPACK}" = "xyes"; then
+      GMSH_DIRS="${GMSH_DIRS} contrib/kbipack"
+      GMSH_LIBS="${GMSH_LIBS} -lGmshKbi -lgmp"
+      cat >>confdefs.h <<\_ACEOF
+#define HAVE_kbipack 1
+_ACEOF
+
+      BO="${BO} kbipack"
     fi
   fi
 
