*** empty log message ***

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -851,6 +851,7 @@ Optional Features:
   --enable-gsl            use GSL as numerical toolkit (default=yes)
   --enable-gui            build the graphical user interface (default=yes)
   --enable-parallel       enable parallel version (default=no)
+  --enable-ann            compile ANN if available (default=yes)
   --enable-triangle       compile Triangle if available (default=yes)
   --enable-netgen         compile Netgen if available (default=yes)
   --enable-tetgen         compile Tetgen if available (default=yes)
@@ -1365,6 +1366,11 @@ fi;
 # Check whether --enable-parallel or --disable-parallel was given.
 if test "${enable_parallel+set}" = set; then
   enableval="$enable_parallel"
+
+fi;
+# Check whether --enable-ann or --disable-ann was given.
+if test "${enable_ann+set}" = set; then
+  enableval="$enable_ann"
 
 fi;
 # Check whether --enable-triangle or --disable-triangle was given.
@@ -3774,6 +3780,56 @@ else
      echo "Please note that by doing so, you agree with Triangle's licensing"
      echo "requirements stated in ./Triangle/README. (Most notably, you may"
      echo "then only redistribute Gmsh if no compensation is received.)"
+     echo "********************************************************************"
+  fi
+fi
+
+
+echo "$as_me:$LINENO: checking for ./ANN/include/ANN/ANN.h" >&5
+echo $ECHO_N "checking for ./ANN/include/ANN/ANN.h... $ECHO_C" >&6
+if test "${ac_cv_file___ANN_include_ANN_ANN_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  test "$cross_compiling" = yes &&
+  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
+echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+if test -r "./ANN/include/ANN/ANN.h"; then
+  ac_cv_file___ANN_include_ANN_ANN_h=yes
+else
+  ac_cv_file___ANN_include_ANN_ANN_h=no
+fi
+fi
+echo "$as_me:$LINENO: result: $ac_cv_file___ANN_include_ANN_ANN_h" >&5
+echo "${ECHO_T}$ac_cv_file___ANN_include_ANN_ANN_h" >&6
+if test $ac_cv_file___ANN_include_ANN_ANN_h = yes; then
+  ANN="yes"
+else
+  ANN="no"
+fi
+
+if test "x${ANN}" = "xyes"; then
+  if test "x$enable_ann" != "xno"; then
+     GMSH_DIRS="${GMSH_DIRS} ANN"
+     GMSH_LIBS="${GMSH_LIBS} -lGmshANN"
+     FLAGS="-DHAVE_ANN_ ${FLAGS}"
+     echo "********************************************************************"
+     echo "You are building a version of Gmsh that contains ANN, the Approximate"
+     echo "Nearest Neighbor library."
+     echo "Please note that by doing so, you agree with ANN's licensing"
+     echo "requirements stated in ./ANN/Copyright.txt."
+     echo "To disable ANN, run configure again with the --disable-ann"
+     echo "option."
+     echo "********************************************************************"
+  fi
+else
+  if test "x$enable_ann" != "xno"; then
+     echo "********************************************************************"
+     echo "If you want to use ANN for doing fast geometrical searchs in the"
+     echo "STL mesher, please download ANN from the"
+     echo "author's web site at http://www.cs.umd.edu/~mount/ANN/,"
+     echo "unpack the archive and copy both src and include directories in the ./ANN subdirectory."
+     echo "Then run ./configure again."
      echo "********************************************************************"
   fi
 fi
