better occ detection (patch from mark van doesburg)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -4868,9 +4868,9 @@ if test "x$enable_occ" = "xyes"; then
   if test "x${OCC_PREFIX}" != "x"; then
     LDFLAGS="-L${OCC_PREFIX}/lib ${LDFLAGS}"
   fi
-  { echo "$as_me:$LINENO: checking for main in -lTKernel" >&5
-echo $ECHO_N "checking for main in -lTKernel... $ECHO_C" >&6; }
-if test "${ac_cv_lib_TKernel_main+set}" = set; then
+  { echo "$as_me:$LINENO: checking for sin in -lTKernel" >&5
+echo $ECHO_N "checking for sin in -lTKernel... $ECHO_C" >&6; }
+if test "${ac_cv_lib_TKernel_sin+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   ac_check_lib_save_LIBS=$LIBS
@@ -4882,11 +4882,17 @@ cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
 
-
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char sin ();
 int
 main ()
 {
-return main ();
+return sin ();
   ;
   return 0;
 }
@@ -4909,22 +4915,88 @@ eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
 	 test ! -s conftest.err
        } && test -s conftest$ac_exeext &&
        $as_test_x conftest$ac_exeext; then
-  ac_cv_lib_TKernel_main=yes
+  ac_cv_lib_TKernel_sin=yes
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-	ac_cv_lib_TKernel_main=no
+	ac_cv_lib_TKernel_sin=no
 fi
 
 rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
       conftest$ac_exeext conftest.$ac_ext
 LIBS=$ac_check_lib_save_LIBS
 fi
-{ echo "$as_me:$LINENO: result: $ac_cv_lib_TKernel_main" >&5
-echo "${ECHO_T}$ac_cv_lib_TKernel_main" >&6; }
-if test $ac_cv_lib_TKernel_main = yes; then
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_TKernel_sin" >&5
+echo "${ECHO_T}$ac_cv_lib_TKernel_sin" >&6; }
+if test $ac_cv_lib_TKernel_sin = yes; then
   OCC="yes"
+else
+  { echo "$as_me:$LINENO: checking for cos in -lTKernel" >&5
+echo $ECHO_N "checking for cos in -lTKernel... $ECHO_C" >&6; }
+if test "${ac_cv_lib_TKernel_cos+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lTKernel "-ldl" $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char cos ();
+int
+main ()
+{
+return cos ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_TKernel_cos=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_TKernel_cos=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_TKernel_cos" >&5
+echo "${ECHO_T}$ac_cv_lib_TKernel_cos" >&6; }
+if test $ac_cv_lib_TKernel_cos = yes; then
+  OCC=yes
+fi
+
 fi
 
   if test "x${OCC}" = "xyes"; then
